services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ragdb
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=${JWT_SECRET}
      - VECTOR_BACKEND=${VECTOR_BACKEND}
    ports:
      - "8000:8000"
    volumes:
      - .:/code 